// auth
export const ADD_TOKEN = "ADD_TOKEN";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
// Notification
export const NOTIFY = "NOTIFY";
export const HIDE = "HIDE";

// Rent
export const ADD_OR_UPDATE_OWNER_DETAILS = "ADD_OR_UPDATE_OWNER_DETAILS";
export const ADD_OR_UPDATE_AGREEMENT = "ADD_OR_UPDATE_AGREEMENT";
export const ADD_OR_UPDATE_PAN_DETAILS = "ADD_OR_UPDATE_PAN_DETAILS";
export const ADD_OR_UPDATE_BILLS = "ADD_OR_UPDATE_BILLS";
export const ADD_OR_UPDATE_BANK = "ADD_OR_UPDATE_BANK";
export const REMOVE_RENT_DETAILS = "REMOVE_RENT_DETAILS";

// User Transactions
export const USER_TO_CUSTOMER_TRANSACTIONS = "USER_TO_CUSTOMER_TRANSACTIONS";
export const USER_TO_SUPPLIER_TRANSACTIONS = "USER_TO_SUPPLIER_TRANSACTIONS";
